apiVersion: v1
kind: Service
metadata:
  name: trading
  labels:
    app: trading
spec:
  ports:
    - port: 80
      targetPort: 5000
  selector:
    app: trading
    tier: app-server
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trading
  labels:
    app: trading
spec:
  replicas: 2
  selector:
    matchLabels:
      app: trading
      tier: app-server
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: trading
        tier: app-server
    spec:
      containers:
      - image: visaganshan/jdbc:latest
        name: trading
        env:
        - name: PSQL_HOST
          value: trading-psql
        - name: PSQL_PORT
          value: "5432"
        - name: "PSQL_DB"
          value: "jrvstrading"
        - name: PSQL_USER
          valueFrom:
            secretKeyRef:
              name: trading-app
              key: user
        - name: PSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: trading-app
              key: password
        ports:
        - containerPort: 5000
          name: trading